version: '3.8'

services:
        db:
          image: mongo:4.4.5
          container_name: db
          restart: always
          environment:
              - MONGO_INITDB_ROOT_USERNAME=dio
              - MONGO_INITDB_ROOT_PASSWORD=dio
          ports:
              - "27017:27017"
          volumes:
              - /home/claudioneves/mongodb-dio/dbdata:/data/db
